/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ambulance.management.gui;

import javax.swing.JOptionPane;
// Import statements should be placed here
import com.ambulance.management.gui.PatientSession;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;



/**
 *
 * @author user
 */
public class MainDashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form MainDashboardForm
     */
    public MainDashboardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        LoginNavigationPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnShowPatientLoginPanel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        LoginModulesPanel = new javax.swing.JPanel();
        AdminLoginPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        btnAdminLogin = new javax.swing.JButton();
        txtAdminPassword = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        PatientLoginPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLogInUsername = new javax.swing.JTextField();
        btnPatientLogin = new javax.swing.JButton();
        txtLogInPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnJumpSignIn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginNavigationPanel.setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Administrator Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        LoginNavigationPanel.add(jButton1);
        jButton1.setBounds(6, 79, 150, 23);

        jButton2.setBackground(new java.awt.Color(51, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Patient Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        LoginNavigationPanel.add(jButton2);
        jButton2.setBounds(200, 80, 130, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ambulance Management System ");
        LoginNavigationPanel.add(jLabel1);
        jLabel1.setBounds(18, 6, 378, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard:");
        LoginNavigationPanel.add(jLabel2);
        jLabel2.setBounds(18, 51, 80, 16);

        btnShowPatientLoginPanel.setBackground(new java.awt.Color(51, 0, 102));
        btnShowPatientLoginPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShowPatientLoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnShowPatientLoginPanel.setText("Patient Login");
        btnShowPatientLoginPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPatientLoginPanelActionPerformed(evt);
            }
        });
        LoginNavigationPanel.add(btnShowPatientLoginPanel);
        btnShowPatientLoginPanel.setBounds(370, 80, 110, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ambulance/management/utils/istockphoto-1185364077-612x612.jpg"))); // NOI18N
        LoginNavigationPanel.add(jLabel10);
        jLabel10.setBounds(-10, 0, 520, 120);

        LoginModulesPanel.setLayout(new java.awt.CardLayout());

        AdminLoginPanel.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Administrator Login");
        AdminLoginPanel.add(jLabel5);
        jLabel5.setBounds(150, 10, 231, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        AdminLoginPanel.add(jLabel3);
        jLabel3.setBounds(80, 60, 130, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        AdminLoginPanel.add(jLabel4);
        jLabel4.setBounds(80, 110, 130, 32);
        AdminLoginPanel.add(txtAdminUsername);
        txtAdminUsername.setBounds(280, 70, 160, 22);

        btnAdminLogin.setBackground(new java.awt.Color(102, 51, 0));
        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLogin.setText("Admin LogIn");
        btnAdminLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });
        AdminLoginPanel.add(btnAdminLogin);
        btnAdminLogin.setBounds(190, 160, 104, 38);
        AdminLoginPanel.add(txtAdminPassword);
        txtAdminPassword.setBounds(280, 120, 160, 22);

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\admin.png")); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminLoginPanel.add(jLabel11);
        jLabel11.setBounds(0, 0, 510, 220);

        LoginModulesPanel.add(AdminLoginPanel, "card2");

        PatientLoginPanel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Patient Login");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientLoginPanel.add(jLabel6);
        jLabel6.setBounds(130, 0, 240, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        PatientLoginPanel.add(jLabel7);
        jLabel7.setBounds(86, 64, 130, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        PatientLoginPanel.add(jLabel8);
        jLabel8.setBounds(86, 108, 130, 32);
        PatientLoginPanel.add(txtLogInUsername);
        txtLogInUsername.setBounds(279, 68, 170, 22);

        btnPatientLogin.setBackground(new java.awt.Color(0, 204, 102));
        btnPatientLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPatientLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnPatientLogin.setText("Login");
        btnPatientLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientLoginActionPerformed(evt);
            }
        });
        PatientLoginPanel.add(btnPatientLogin);
        btnPatientLogin.setBounds(90, 170, 100, 40);
        PatientLoginPanel.add(txtLogInPassword);
        txtLogInPassword.setBounds(279, 112, 170, 22);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Don't have an Account? ");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientLoginPanel.add(jLabel9);
        jLabel9.setBounds(300, 160, 129, 20);

        btnJumpSignIn.setBackground(new java.awt.Color(51, 153, 255));
        btnJumpSignIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnJumpSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnJumpSignIn.setText("Sign-In");
        btnJumpSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJumpSignInActionPerformed(evt);
            }
        });
        PatientLoginPanel.add(btnJumpSignIn);
        btnJumpSignIn.setBounds(330, 180, 72, 23);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\login patient.jpg")); // NOI18N
        jLabel13.setToolTipText("");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PatientLoginPanel.add(jLabel13);
        jLabel13.setBounds(0, 0, 540, 250);

        LoginModulesPanel.add(PatientLoginPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginModulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addComponent(LoginNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginModulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginModulesPanel.removeAll();
       
        LoginModulesPanel.add(AdminLoginPanel);
        LoginModulesPanel.repaint();
        LoginModulesPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnJumpSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJumpSignInActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnJumpSignInActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PatientRequestForm form =new PatientRequestForm();    
        form.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnShowPatientLoginPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPatientLoginPanelActionPerformed
        LoginModulesPanel.removeAll();     
        LoginModulesPanel.add(PatientLoginPanel);
        LoginModulesPanel.repaint();
        LoginModulesPanel.revalidate();         // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPatientLoginPanelActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        String username = txtAdminUsername.getText();
     String password = new String(txtAdminPassword.getPassword()); 

     // TODO: add your handling code here:
     if ("Admin".equals(username) && "admin".equals(password)) {
         AmbulanceManagerFromPanel ab = new AmbulanceManagerFromPanel();
         ab.setVisible(true);
     } else {
         JOptionPane.showMessageDialog(this, "Invalid login. Please check your credentials.");
     }

    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnPatientLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientLoginActionPerformed
        // TODO add your handling code here:
        loginPatient();
    }//GEN-LAST:event_btnPatientLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminLoginPanel;
    private javax.swing.JPanel LoginModulesPanel;
    private javax.swing.JPanel LoginNavigationPanel;
    private javax.swing.JPanel PatientLoginPanel;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnJumpSignIn;
    private javax.swing.JButton btnPatientLogin;
    private javax.swing.JButton btnShowPatientLoginPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JTextField txtAdminUsername;
    private javax.swing.JPasswordField txtLogInPassword;
    private javax.swing.JTextField txtLogInUsername;
    // End of variables declaration//GEN-END:variables

      private void loginPatient() {
    // Database connection details
    String url = "jdbc:mysql://localhost:3306/AmbulanceManagementSystem";
    String username = "root";
    String password = "mysql";

    // Get login credentials
    String patientUsername = txtLogInUsername.getText();
    String patientPassword = new String(txtLogInPassword.getPassword());

    // Ensure fields are not empty
    if (patientUsername.isEmpty() || patientPassword.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username and password are required.");
        return;
    }

    // SQL query
    String query = "SELECT patient_id, name FROM Patient WHERE username = ? AND password = ?";

    try (Connection conn = DriverManager.getConnection(url, username, password);
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setString(1, patientUsername);
        stmt.setString(2, patientPassword);

        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                int patientId = rs.getInt("patient_id");
                String patientName = rs.getString("name");

                JOptionPane.showMessageDialog(null, "Login successful! Welcome, " + patientName);
                PatientSession.getInstance().setPatientId(patientId);
                PatientAssignment pa=new PatientAssignment();
                
                this.dispose();
                pa.setVisible(true);

                
 
                
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error during login: " + e.getMessage());
    }
}

}
